name: Deploy Fitple

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Fitple
        working-directory: Fitple
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DD_HHmmss
          utcOffset: "+09:00"

      - name: Set artifact
        working-directory: Fitple
        run: echo "artifact=$(basename $(ls ./build/libs/*.jar | grep -v plain))" >> $GITHUB_ENV

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: springboot-developer
          environment_name: springboot-developer-env-1
          version_label: fitple-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: Fitple/build/libs/${{ env.artifact }}
